[package]
name = "plexrs"
version = "0.1.0"
authors = ["Dan Cardin <ddcardin@gmail.com>"]
edition = "2018"

[dependencies]
crossterm = "*"
os_pipe = "0.9.1"

[[bin]]
name = "plexrs"
doc = false

[lib]
doc = true
